package com.dhanu.kurio.core.design.color

import androidx.compose.ui.graphics.Color

object KurioColors {
    val Primary = Color(0xFF24443D)
    val PrimaryVariant = Color(0xFF16312B)
    val OnPrimary = Color(0xFFFFFFFF)
    val Secondary = Color(0xFF68736F)
    val SecondaryVariant = Color(0xFF3F4945)
    val OnSecondary = Color(0xFFFFFFFF)
    val Background = Color(0xFFF7F7F3)
    val Surface = Color(0xFFFFFFFF)
    val SurfaceVariant = Color(0xFFEFF1EC)
    val PrimaryText = Color(0xFF161A18)
    val SecondaryText = Color(0xFF65706B)
    val Accent = Color(0xFF2C6F62)
    val Success = Color(0xFF2C6F62)
    val Error = Color(0xFFB84A3A)
    val Warning = Color(0xFF9B6A21)
    val Border = Color(0xFFDDE2DA)
    val Divider = Color(0xFFE8EBE5)
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
    val SurfaceContainer = Color(0xFFFFFFFF)
    val SecondarySurface = Color(0xFFEFF1EC)

    val DarkPrimary = Color(0xFFA6D3C7)
    val DarkPrimaryVariant = Color(0xFF7FB4A7)
    val DarkOnPrimary = Color(0xFF08231E)
    val DarkSecondary = Color(0xFFB8C4BE)
    val DarkSecondaryVariant = Color(0xFFDDE7E1)
    val DarkOnSecondary = Color(0xFF17211D)
    val DarkBackground = Color(0xFF111513)
    val DarkSurface = Color(0xFF1A201D)
    val DarkSurfaceVariant = Color(0xFF232B27)
    val DarkPrimaryText = Color(0xFFE7ECE7)
    val DarkSecondaryText = Color(0xFFAAB5AF)
    val DarkAccent = Color(0xFFA6D3C7)
    val DarkSuccess = Color(0xFF83C7B5)
    val DarkError = Color(0xFFE39A8E)
    val DarkWarning = Color(0xFFE0B46F)
    val DarkBorder = Color(0xFF34403A)
    val DarkDivider = Color(0xFF2A332F)
    val DarkSurfaceContainer = Color(0xFF1A201D)
    val DarkSecondarySurface = Color(0xFF232B27)
}
