package com.dhanu.kurio.core.design.color

import androidx.compose.ui.graphics.Color

object KurioColors {
    val Primary = Color(0xFF1A73E8)
    val PrimaryVariant = Color(0xFF1557B0)
    val OnPrimary = Color(0xFFFFFFFF)
    val Secondary = Color(0xFF5F6368)
    val SecondaryVariant = Color(0xFF3C4043)
    val OnSecondary = Color(0xFFFFFFFF)
    val Background = Color(0xFFF8F9FA)
    val Surface = Color(0xFFFFFFFF)
    val SurfaceVariant = Color(0xFFF1F3F4)
    val PrimaryText = Color(0xFF202124)
    val SecondaryText = Color(0xFF5F6368)
    val Accent = Color(0xFF1A73E8)
    val Success = Color(0xFF1E8E3E)
    val Error = Color(0xFFD93025)
    val Warning = Color(0xFFF9AB00)
    val Border = Color(0xFFDADCE0)
    val Divider = Color(0xFFE8EAED)
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
    val SurfaceContainer = Color(0xFFFFFFFF)
    val SecondarySurface = Color(0xFFF1F3F4)

    val DarkPrimary = Color(0xFF8AB4F8)
    val DarkPrimaryVariant = Color(0xFF669DF6)
    val DarkOnPrimary = Color(0xFF062E6F)
    val DarkSecondary = Color(0xFFC4C7C5)
    val DarkSecondaryVariant = Color(0xFFE8EAED)
    val DarkOnSecondary = Color(0xFF1F1F1F)
    val DarkBackground = Color(0xFF1F1F1F)
    val DarkSurface = Color(0xFF2D2D2D)
    val DarkSurfaceVariant = Color(0xFF353535)
    val DarkPrimaryText = Color(0xFFE8EAED)
    val DarkSecondaryText = Color(0xFF9AA0A6)
    val DarkAccent = Color(0xFF8AB4F8)
    val DarkSuccess = Color(0xFF81C995)
    val DarkError = Color(0xFFF28B82)
    val DarkWarning = Color(0xFFFDD663)
    val DarkBorder = Color(0xFF5F6368)
    val DarkDivider = Color(0xFF3C4043)
    val DarkSurfaceContainer = Color(0xFF2D2D2D)
    val DarkSecondarySurface = Color(0xFF353535)
}
