package com.dhanu.kurio.core.model

object SpeechModelRegistry {
    fun getDefaultModels(): List<SpeechModel> {
        return listOf(
            SpeechModel(
                id = "whisper-tiny-en",
                name = "Whisper Tiny English",
                description = "Lightweight English-only model for fast transcription",
                provider = "OpenAI",
                license = "MIT",
                language = "English",
                sizeBytes = 39_000_000,
                ramUsageMb = 256,
                speedRating = 5,
                accuracyRating = 3,
                downloadUrl = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
                checksum = "",
                version = "1.0.0",
                recommendedDeviceClass = DeviceClass.LOW_END,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = false
            ),
            SpeechModel(
                id = "whisper-tiny",
                name = "Whisper Tiny Multilingual",
                description = "Multilingual model supporting multiple languages",
                provider = "OpenAI",
                license = "MIT",
                language = "Multilingual",
                sizeBytes = 75_000_000,
                ramUsageMb = 390,
                speedRating = 4,
                accuracyRating = 4,
                downloadUrl = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
                checksum = "",
                version = "1.0.0",
                recommendedDeviceClass = DeviceClass.MID_RANGE,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = false
            ),
            SpeechModel(
                id = "whisper-base-en",
                name = "Whisper Base English",
                description = "More accurate English-only model",
                provider = "OpenAI",
                license = "MIT",
                language = "English",
                sizeBytes = 74_000_000,
                ramUsageMb = 500,
                speedRating = 3,
                accuracyRating = 4,
                downloadUrl = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin",
                checksum = "",
                version = "1.0.0",
                recommendedDeviceClass = DeviceClass.MID_RANGE,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = false
            ),
            SpeechModel(
                id = "whisper-base",
                name = "Whisper Base Multilingual",
                description = "Accurate multilingual transcription",
                provider = "OpenAI",
                license = "MIT",
                language = "Multilingual",
                sizeBytes = 145_000_000,
                ramUsageMb = 700,
                speedRating = 2,
                accuracyRating = 5,
                downloadUrl = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
                checksum = "",
                version = "1.0.0",
                recommendedDeviceClass = DeviceClass.HIGH_END,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = false
            ),
            SpeechModel(
                id = "moonshine-tiny",
                name = "Moonshine Tiny",
                description = "Experimental ultra-fast mobile transcription model",
                provider = "Useful Sensors",
                license = "Apache-2.0",
                language = "English",
                sizeBytes = 25_000_000,
                ramUsageMb = 128,
                speedRating = 5,
                accuracyRating = 3,
                downloadUrl = "",
                checksum = "",
                version = "0.1.0",
                recommendedDeviceClass = DeviceClass.LOW_END,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = true
            ),
            SpeechModel(
                id = "moonshine-base",
                name = "Moonshine Base",
                description = "Experimental improved accuracy model",
                provider = "Useful Sensors",
                license = "Apache-2.0",
                language = "English",
                sizeBytes = 50_000_000,
                ramUsageMb = 256,
                speedRating = 4,
                accuracyRating = 4,
                downloadUrl = "",
                checksum = "",
                version = "0.1.0",
                recommendedDeviceClass = DeviceClass.MID_RANGE,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = true
            ),
            SpeechModel(
                id = "vosk-small-en",
                name = "Vosk Small English",
                description = "Very low-end device optimized model",
                provider = "Alpha Cephei",
                license = "Apache-2.0",
                language = "English",
                sizeBytes = 20_000_000,
                ramUsageMb = 96,
                speedRating = 5,
                accuracyRating = 2,
                downloadUrl = "",
                checksum = "",
                version = "0.3.0",
                recommendedDeviceClass = DeviceClass.LOW_END,
                status = ModelStatus.NOT_DOWNLOADED,
                isExperimental = true
            )
        )
    }
}
